- bin/gh-pages
- package.json
- readme.md
```shell
$ npm install gh-pages -g
$ gh-pages -d dist -b master
```
> Support command line

- bin/gh-pages
It may be convenient to support & expose the `add` option to the cli executable.
> Added support for the --add option to cli.

- bin/gh-pages
always handle error argument in a callback
> Make CLI exit with error if publishing fails

- lib/index.js
- provide error handling for callback
- provide default error handling if no callback is passed
> better error handling

- bin/gh-pages
This is a refreshed version of #19, adding support for a `--message` option to the CLI.
> Add message option to cli

- lib/index.js
- package.json
- readme.md
With this change, `src` can be a single pattern or an array of patterns.
Fixes #29.
> Allow an array of src patterns to be provided

- bin/gh-pages
This exposes a `remove` option to the CLI.  If a pattern is provided, only the matching files will be removed from the existing `dist` directory.  To leave just a single file, pattern negation can be used.  E.g.
```
gh-pages --remove '!CNAME'
```
Fixes #74.
> Expose a "remove" option to the CLI

- lib/index.js
- package.json
This uses `rimraf` instead of `wrench` for cleaning the cache directory.
Fixes #77.
> Use rimraf for cleaning

- bin/gh-pages
- lib/git.js
- lib/index.js
This is an alternative to #162.  This exposes the `depth` to the CLI and makes the default `1`.
> Clone with depth 1 by default

- bin/gh-pages
- lib/index.js
- package.json
- plugin.js
- readme.md
To debug the `gh-pages` script, set `NODE_DEBUG=gh-pages`.
> Remove the logger option and use util.debuglog()

- .travis.yml
- bin/gh-pages.js
- lib/git.js
- lib/index.js
- lib/util.js
- package-lock.json
- package.json
- readme.md
- test/bin/gh-pages.spec.js
- test/helper.js
- test/integration/basic.spec.js
- test/integration/dest.spec.js
- test/integration/include.spec.js
- test/lib/util.spec.js
When the `gh-pages` command runs, it creates a repo in a cache directory.  By default, this directory is in the `gh-pages` install directory (e.g. `path/to/node_modules/gh-pages/.cache`).
Previously, commits that were created in the cached repo used the `git config user.email` and `git config user.name` as determined from the cached repo.  In the case of a global `gh-pages` install, this user name and email would most likely be the global git user.  In the case of a local `gh-pages` install, this would be a local git user if one was configured.
This branch changes things so that the user is determined by running `git config user.email` (and same for name) in the current working directory.  This means that the git user will be the local user if the current directory is a git repo and has a …
> Better user handling

- bin/gh-pages.js
This PR is based #23 to enable the '--git' so we can set the path to git.
> support '--git' CLI option

- bin/gh-pages.js
- lib/index.js
- test/bin/gh-pages.spec.js
Support for a `--git` option was added in #303 and released in 2.1.0.  Because a default value was not provided, this broke all use without the `--git` option.  This fixes that.
Thanks @webkadiz for the proposed fix in #311 and @nytamin for #309.
Fixes #308.
> Add default value for git option

- bin/gh-pages.js
- lib/git.js
- lib/index.js
- readme.md
- test/bin/gh-pages.spec.js
Implemented with reference to `keep-history` of [Travis GitHub Pages Deployment](https://docs.travis-ci.com/user/deployment/pages/).
> cli: add `--no-history` flag not to preserve deploy history

- readme.md
I added documentation about the 'remove' option to the readme.
> Added 'remove' documentation to the readme

- bin/gh-pages.js
It allows using an absolute path to start with `/` as the dist directory. The use case is it can be used the dist directory as a path not be under the current directory.
It might be a breaking change because of behavior changes on a pass a path to start with `/`. Please bump a major version if needed.
Fixes: #317
> Allow an absolute path as dist directory

- .prettierrc
- bin/gh-pages.js
- lib/git.js
- lib/index.js
- test/integration/fixtures/remove/expected/new.js
- test/integration/fixtures/remove/expected/stable.txt
- test/integration/fixtures/remove/local/new.js
- test/integration/fixtures/remove/remote/removed.css
- test/integration/fixtures/remove/remote/removed.js
- test/integration/fixtures/remove/remote/stable.txt
- test/integration/remove.spec.js
This PR fixes some issues described below and resolves #334, fixes #337 .
https://github.com/tschaub/gh-pages/blob/3579ab235d5502a2a1dc4d2f18ec1c9dce03f94a/lib/index.js#L156
Joining files in a string causes incorrect shell argument passing. A globbed file can be removed, but globbed files cannot be removed since the actual command will be
```
git rm -r -f "abc.js abc.css"
```
This PR makes `git.rm` and `git.add` accept `string[]` and handle them properly.
https://github.com/tschaub/gh-pages/blob/3579ab235d5502a2a1dc4d2f18ec1c9dce03f94a/lib/index.js#L97-L99
This shows that **gh-pages** globs files to be removed in local dist directory, not in remote branch. It causes git a fatal error(like #337) since it tries to remove files that are not in remote dist directory. `globby.sync` should be …
> Fix remove not working properly

- bin/gh-pages.js
- lib/index.js
- readme.md
- test/bin/fixtures/beforeAdd.js
- test/bin/gh-pages.spec.js
- test/integration/beforeAdd.spec.js
- test/integration/fixtures/beforeAdd/expected/hello-old-world.txt
- test/integration/fixtures/beforeAdd/expected/hello-world.txt
- test/integration/fixtures/beforeAdd/local/hello-world.txt
- test/integration/fixtures/beforeAdd/remote/hello-old-world.txt
- test/integration/fixtures/beforeAdd/remote/hello-outdated-world.txt
As proposed in https://github.com/tschaub/gh-pages/issues/331
> feat(beforeAdd): allow custom script before git add

- readme.md
I added just the command lines for `--repo` and `--branch`. Let me know the others if you want them added to this pull request.
> Update readme with command line options

- .github/workflows/test.yml
- package-lock.json
- package.json
- readme.md
This updates development dependencies to address security warnings.  Because the updated test dependencies no longer support Node < 10, tests are no longer run on Node < 10.  The library itself will still likely work on older Node modules, but no tests will be run there.
> Dev dependency updates

- readme.md
Please see #368 for the full breakdown of this addition. Due to issues with a fork, that PR needed to be recreated to be properly updated.
The updates to the original PR include minor adjustments to the URL when defining the step and some minor formatting improvements, as well as the addition of a section describing how to use named scripts inside the Action(s).
> Add GitHub Actions tips to readme.md

- package-lock.json
- package.json
regenerated lock file from scratch to get back to 0 vulnerabilities
fixes:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ normalize-url                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.5.1 <5.0.0 || >=5.3.1 <6.0.0 || >=6.0.1                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gh-pages                                                     │
├───────────────┼──────────────────────────────────────────────────────── …
```
> security(deps): bump filenamify-url to 2.1.1

- lib/index.js
- package-lock.json
- package.json
- test/lib/index.spec.js
to prevent URL check failures blocking publishing.
related #394 #392
As my finding ( https://github.com/tschaub/gh-pages/issues/394#issuecomment-861920146 ) that `filenamify-url` is doing URL check but git repo URLs may fail the check and this dependency is only used to generate cache filename. I think it is safe to use only `filenamify`.
Fixes #392.
> Switch from filenamify-url to filenamify

- .github/workflows/test.yml
- bin/gh-pages-clean.js
- bin/gh-pages.js
- lib/git.js
- lib/index.js
- lib/util.js
- package-lock.json
- package.json
- plugin.js
- readme.md
- test/bin/gh-pages.spec.js
- test/helper.js
- test/integration/basic.spec.js
- test/integration/beforeAdd.spec.js
- test/integration/dest.spec.js
- test/integration/include.spec.js
- test/integration/remove.spec.js
- test/lib/index.spec.js
- test/lib/util.spec.js
This updates the development dependencies and changes formatting to satisfy the linter.
> Updated dev dependencies and formatting

- .github/dependabot.yml
- .github/workflows/test.yml
- lib/index.js
- lib/util.js
- package-lock.json
- package.json
- test/helper.js
Changes:
* use of `Set` instead of an object for the set of unique directories (fixes #446)
* updated development dependencies
* the `publish` function now always returns a promise (previously it returned `undefined` in some error cases)
* stop testing on Node v12, start testing on v18 (due to development dependency updates, the lib should still work on 12)
> Assorted updates

- readme.md
I've noticed a common misconception about GitHub Pages, specifically _project_ sites that are not served at the root `<user|org>.github.io` domain and instead under a `/<repo>` path.
Some example issues for the `gh-pages` project that reflect this:
- https://github.com/tschaub/gh-pages/issues/285
- https://github.com/tschaub/gh-pages/issues/233
- https://github.com/tschaub/gh-pages/issues/414
- https://github.com/tschaub/gh-pages/issues/351
- https://github.com/tschaub/gh-pages/issues/296
- https://github.com/tschaub/gh-pages/issues/227
- https://github.com/tschaub/gh-pages/issues/184
The only way I can think to alleviate this is to address it right in the project's `README.md`, hence this PR.
> Update README to clarify project site configuration requirements with tools like CRA, webpack, Vite, etc.

- readme.md
CNAME file doesn't work if there are quotation marks in the domain, I had trouble with my own due to copying and pasting this command as it is. Removing the quotations made it work again.
> Remove quotation marks

- bin/gh-pages.js
- test/bin/gh-pages.spec.js
Fixes #354 by adding a descriptive message.
```bash
❯ npx gh-pages .
The "paths[1]" argument must be of type string. Received undefined
```
```bash
❯ npx gh-pages .
No base directory specified. The `--dist` option must be specified.
```
I also used `Command()` instead of the singleton `CommanderStatic`, since it makes it more testable.
With `const program = require('commander');`, values like `program.user` were being carried from previous tests 👍
> Add error message when --dist is not specified.

- .github/workflows/test.yml
- bin/gh-pages.js
- package-lock.json
- package.json
- readme.md
- test/bin/gh-pages.spec.js
This change updates `commander` to make use of the `requiredOption` function for the `--dist` option.
> Dependency updates and drop Node 14

- bin/gh-pages.js
- lib/index.js
- readme.md
- test/bin/gh-pages.spec.js
- test/integration/cname.spec.js
- test/integration/fixtures/cname/expected/CNAME
- test/integration/fixtures/cname/expected/hello-world.txt
- test/integration/fixtures/cname/local/hello-world.txt
- test/integration/fixtures/nojekyll-exists/expected/hello-world.txt
- test/integration/fixtures/nojekyll-exists/local/hello-world.txt
- test/integration/fixtures/nojekyll/expected/hello-world.txt
- test/integration/fixtures/nojekyll/local/hello-world.txt
- test/integration/nojekyll.spec.js
- test/integration/nojekyllExists.spec.js
The `--nojekyll` option can be used to write out a `.nojekyll` file.
The `--cname` option can be used to write a `CNAME` file with a custom domain name.
Closes #503
Closes #468
Closes #467
Closes #371
Closes #347
Closes #321
Closes #179
Closes #127
Closes #74
Closes #34
> Add --nojekyll and --cname options

- bin/gh-pages.js
- lib/index.js
- test/bin/gh-pages.spec.js
- test/integration/cnameExists.spec.js
- test/integration/fixtures/cname-exists/expected/CNAME
- test/integration/fixtures/cname-exists/expected/hello-world.txt
- test/integration/fixtures/cname-exists/local/hello-world.txt
- test/integration/fixtures/cname-exists/remote/CNAME
The `--cname <CNAME>` option added in #533 is not passed to the config, thus this option doesn't work in the current release. This includes that option and adds a test for the missing case.
Reviewing the original PR, the only other difference I see is that there's a `nojekyll-exists` spec but not a `cname-exists` spec - if there's a desire to have that as well I can add it.
> fix: Add missing cname option not passed to the config

- lib/git.js
This fix ensures `gh-pages` correctly handles files with names starting with a `-`. By adding `--` to the `git rm` command, filenames are treated as file paths instead of options. This prevents errors during deployment.
> fixes #592

- lib/index.js
- readme.md
* Default option `remove` is changed from `'.'` to `'**/{,.}*'`.
* The new glob pattern matches ordinary files and dotfiles, guaranteeing a truly clean working directory before publishing.
1. Glob `'.'` (or `*`, or `**/*`) ignores dotfiles – The old pattern skipped hidden files such as `.gitignore`, `.nojekyll`, or any project-specific dotfile, leaving them behind between deploys.
2. First-time deploy contamination – When gh-pages checks out a brand-new branch from the current branch, existing dotfiles are copied over, polluting the freshly created branch.
* Users with custom remove settings are unaffected.
* Users who relied on the old “keep dotfiles” behavior (expected to be rare) will now see those files removed; they can keep the old behavior by explicitly setting remove.
* Consider …
> [Bugfix] make default remove glob match dotfiles
