tschaub/gh-pages

bin/gh-pages, lib/index.js, package.json
This reworks the changes in #36 a bit to consistently use the configured logger.
=> Rework callback error handling

bin/gh-pages
=> Add --silent option to the bin

package.json
This brings in ESLint v2 and an updated config.
=> Ugrade ESLint and config

bin/gh-pages, lib/git.js, lib/index.js, readme.md
This fleshes out the support for a custom remote.  Thanks @marco-c for the original work in #24.
=> Support a custom remote

.travis.yml, lib/git.js, package.json
This updates the dependencies.
=> Updates dependencies

lib/index.js, package.json
This makes explicit the dependency on Node 4+.
=> Require Node 4+

bin/gh-pages, package.json, test/bin/gh-pages.spec.js, test/helper.js
This is a reworked version of #71.  Thanks @thiagofelix for the contribution.
Fixes #56.
=> Fix noPush command argument and include regression tests for the CLI

bin/gh-pages, lib/index.js, readme.md, test/bin/gh-pages.spec.js, test/helper.js, test/integration/basic.spec.js, test/integration/dest.spec.js, test/integration/fixtures/basic/expected/hello-world.txt, test/integration/fixtures/dest/expected/stable.txt, test/integration/fixtures/dest/remote/stable.txt, test/integration/fixtures/dest/remote/target/removed.txt, test/integration/fixtures/include/expected/good.js
This allows publishing to a sub-directory within the target repo/branch.
Thanks @lelandmiller for the original contribution in #30.
=> Add a dest option

lib/util.js, test/lib/util.spec.js
This is a reworked version of #85.  Thanks @esarbanis for the contribution.
Fixes #16
=> Provision for root path when splitting

bin/gh-pages-clean, lib/index.js, package.json
This clones repos in their own directories.
Fixes #58.
=> Dedicated cache directory per repo

package.json
=> fix(package): update async to version 2.5.0

package.json
=> fix(package): update commander to version 2.11.0

package.json
=> chore(package): update sinon to version 2.3.3

lib/index.js
Make the publish function return the promise so that the functionality can be used in scripts to run stuff afterwards
=> Return the promise in the publish function

.travis.yml, package-lock.json, package.json
=> Update dependencies, test on Node 8

package.json
=> fix(package): update commander to version 2.15.1

readme.md
many people got confuse and wasting time cause this simple tip.
=> docs(readme.md): add tips

lib/index.js
Fixes #267 (although it may just reveal another failure later).
=> Guard against no configured user

package-lock.json, package.json, test/bin/gh-pages.spec.js
This updates dev dependencies and adds a test for the `--git` option added in #303.
=> Dev dependency updates

lib/index.js, package-lock.json, package.json, readme.md
This moves the location of the cache directory in hopes of working with yarn.
Fixes #343
=> Move the cache directory

readme.md
The information about the custom domain should be in the documentation. I found it in the issues, but it should be documented. 
Addresses #347 #213 #127 #34
=> Add note about domain problem

.github/workflows/test.yml, package-lock.json, package.json
This updates dev dependencies.
=> Update dev dependencies

package-lock.json, package.json
Reverts tschaub/gh-pages#393
Fixes #394
=> Revert "security(deps): bump filenamify-url to 2.1.1"

readme.md
Tested on my [personal project](https://github.com/multivoltage/react-use-zendesk) on github
=> fix: update instruction for next.js

bin/gh-pages.js, lib/index.js, test/bin/gh-pages.spec.js
=> More async/await

lib/index.js, package-lock.json, package.json
https://npmgraph.js.org/?q=globby - 23 dependencies
https://npmgraph.js.org/?q=tinyglobby - 2 dependencies
=> chore: switch to tinyglobby
